# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestTestOne():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testOne(self):
    self.driver.get("https://astro.ucla.edu/~wright/CosmoCalc.html")
    self.driver.set_window_size(1296, 741)
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.NAME, "txtz").click()
    self.driver.find_element(By.NAME, "txtz").send_keys("4")
    self.driver.find_element(By.NAME, "Flat").click()
    
     # Esperar hasta que el texto del "Angular Size Distance D" sea visible
    angular_distance_element = WebDriverWait(self.driver, 10).until(
      EC.visibility_of_element_located((By.XPATH, "//b[contains(text(), 'angular size distance D')]/following-sibling::text()"))
    )

      # Obtener el texto correspondiente a la distancia angular
    angular_distance_text = angular_distance_element.text

    # Imprimir el resultado
    print(f"Angular Size Distance D: {angular_distance_text}")
  
if __name__ == "__main__":
    test = TestTestOne()
    test.setup_method(None)
    test.test_testOne()
    test.teardown_method(None)